name: hello
description: Emergency SOS Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Map
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  
  # Date formatting
  intl: ^0.18.1
  
  # Image picker for media upload
  image_picker: ^1.0.4

  google_sign_in: ^6.2.1

  # HTTP requests (for future API integration)
  http: ^1.1.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true